name: Spotify Auth Proxy
on:
  push:
    branches:
      - main
jobs:
  run-spotify-auth-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Spotify Auth Proxy
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          echo "SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}" > .env
          echo "SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}" >> .env
          docker run -d --name spotify-auth-proxy -p 27228:27228 --env-file ./.env ghcr.io/conradludgate/spotify-auth-proxy
          docker logs -f spotify-auth-proxy
          docker stop spotify-auth-proxy
          docker rm spotify-auth-proxy
