name: Spotify Auth Proxy
on:
  push:
    branches:
      - main
jobs:
  run-spotify-auth-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Run Spotify Auth Proxy
        run: |
          docker run --rm -p 27228:27228 \
            -e SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} \
            -e SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} \
            ghcr.io/conradludgate/spotify-auth-proxy
          docker logs $(docker ps -q --filter ancestor=ghcr.io/conradludgate/spotify-auth-proxy)
